// data.ts
export const eventData = [
    {
        id: 1,
        category: "Technical",
        date: "1 March",
        title: "TrailBlazer",
        description: "Participants will compete with their IOT based line tracing car & the one to reach the end in minimum time will win.",
        rounds: "2",
        team: "Solo",
        price: "50",
        coordinators: [
          { name: "Krishna B", contact: "8780751157" },
        ],
        imageSrc: "poster/1.png",
      },
      {
        id: 2,
        category: "Technical",
        date: "1 March & 2 March",
        title: "Tech Shastrarth",
        description: "A technology will be given . One team will debate on its pros and other will debate on its cons. Best team will be the winner.",
        rounds: "2",
        team: "4 Members",
        price: "100",
        coordinators: [
          { name: "Raghav", contact: "9106546270" },
          { name: "Tapan", contact: "7283839765" },
        ],
        imageSrc: "poster/2.png",
      },
      {
        id: 3,
        category: "Technical",
        date: "2 March",
        title: "Tech Showdown",
        description: "A technology will be given . One team will debate on its pros and other will debate on its cons. Best team will be the winner.",
        rounds: "3",
        team: "4 Members",
        price: "100",
        coordinators: [
          { name: "Vaishnavi", contact: "6355384251" },
        ],
        imageSrc: "poster/3.png",
      },
      {
        id: 4,
        category: "Technical",
        date: "2 March",
        title: "Lightning Relay-ers",
        description: "Participants will form a group to participate. The first person in the group starts coding after the time's up the next player takes over and so on the game is continued till the last player.",
        rounds: "2",
        team: "5 Members",
        price: "100",
        coordinators: [
          { name: "Prashant", contact: "-" },
    
        ],
        imageSrc: "poster/4.png",
      },
      {
        id: 5,
        category: "Technical",
        date: "1 March",
        title: "Code Crisis",
        description: "code will be provided along /with the desired output and participants have to find out as much errors as they can and rectify it",
        rounds: "2",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Aryan Hotchandani", contact: "9106464264" },
        ],
        imageSrc: "poster/5.png",
      },
      {
        id: 6,
        category: "Technical",
        date: "2 March",
        title: "Unfinished Dojo",
        description: "participants have to fill in the code snippets according to the desired output based on their applied logic.",
        rounds: "2",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Raj", contact: "9100000000" },
        ],
        imageSrc: "poster/6.png",
      },
      {
        id: 7,
        category: "Technical",
        date: "1 March",
        title: "Webify",
        description: "Participants will have to design a website based on a prompt given to them.",
        rounds: "3",
        team: "Solo/2 Members",
        price: "50",
        coordinators: [
          { name: "Krish Panchani", contact: "8866799347" },
        ],
        imageSrc: "poster/7.png",
      }, 
      {
        id: 8,
        category: "Technical",
        date: "1 March",
        title: "Blockly",
        description: "coders will drag and drop blocks of code snippets using blockly software ",
        rounds: "3",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Manmohan", contact: "7232010574" },
        ],
        imageSrc: "poster/8.png",
      },
      {
        id: 9,
        category: "Technical",
        date: "2 March",
        title: "Pixel Party",
        description: "All teams will design creative interface. The design with best working and interface will win.",
        rounds: "2",
        team: "Solo/2 Members",
        price: "50",
        coordinators: [
          { name: "Presha", contact: "8799027624" },
        ],
        imageSrc: "poster/9.png",
      },
      {
        id: 10,
        category: "Technical",
        date: "1 March",
        title: "Codin' Dark",
        description: "participants have to code without looking at the monitor and their accuracy will be checked.",
        rounds: "3",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Prachi", contact: "6358031500" },
        ],
        imageSrc: "poster/10.png",
      },
      {
        id: 11,
        category: "Technical",
        date: "1 March & 2 March",
        title: "ShellSeekers",
        description: "Participants have to find the hidden Flag or hints and solve security related puzzle to find and exploits vulnerabilities by using Basic LINUX and CLI commands.",
        rounds: "2",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Meet Katarmal", contact: "9137674983" },
          { name: "Karan Bharda", contact: "7048458658" },
        ],
        imageSrc: "poster/11-1.png",
      },
      {
        id: 12,
        category: "Technical",
        date: "1 March",
        title: "spur-of-the-moment",
        description: "Particpants will be given the topic on the spot and they have to speak on that topic.",
        rounds: "1/2",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Sarthi Vyas", contact: "9100000000" },
        ],
        imageSrc: "posters/Spur-Of-The-Moment.svg",
      },
      {
        id: 13,
        category: "Technical",
        date: "1 March",
        title: "Mechanical Quizzard",
        description: "All teams will be asked a general question and the team that answers first will go to next round(written round).",
        rounds: "3",
        team: "2 Members",
        price: "50",
        coordinators: [
          { name: "Nikhil", contact: "9100000000" },
        ],
        imageSrc: "posters/Mechanical_Quizzard.svg",
      },
      {
        id: 14,
        category: "Technical",
        date: "2 March",
        title: "Cadathon",
        description: "Cadathon is online drawing competition in which individual should submit Autocad 2D drawing detailed report in specific time satisfying given problem.",
        rounds: "1",
        team: "Solo",
        price: "50",
        coordinators: [
          { name: "Vivek", contact: "0000000000" },
        ],
        imageSrc: "posters/trailblazer.svg",
      },
      {
        id: 15,
        category: "Technical",
        date: "1 March",
        title: "Simtronics",
        description: "Participants will  have to do circuit making on the breadboard as well as software tool.",
        rounds: "2",
        team: "2 Members",
        price: "80",
        coordinators: [
          { name: "Rushil Patel", contact: "8160266095" },
        ],
        imageSrc: "posters/Simtronics.svg",
      },
      {
        id: 16,
        category: "Technical",
        date: "2 March",
        title: "Mindset melee",
        description: "Participants have to attempt the mcqs,audio visual and rapid fire questions the team having maxium points will be winner.",
        rounds: "4",
        team: "2 Members",
        price: "40",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "posters/Mindset_Melee.svg",
      },
      {
        id: 17,
        category: "Technical",
        date: "1 March",
        title: "Money Heist",
        description: "Specific amount will be given to the students they have to design budget.",
        rounds: "2",
        team: "4 Members",
        price: "80",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "posters/Money_Heist.svg",
      },
      {
        id: 18,
        category: "Technical",
        date: "1 March",
        title: "Shelby Surge",
        description: "A existing company's logo will be given to the students they have to frame the logo by using their creativity.",
        rounds: "1",
        team: "Solo",
        price: "50",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "posters/Shelby_Surge.svg",
      },
      {
        id: 19,
        category: "Non-Technical",
        date: "2 March",
        title: "Image-Gen",
        description: "Participants have to make posters of AIT TechFest using different AI Image Generation Tool. they can use thier creative thinking to make posters and give prompt to AI Tool. Best Poster Design will win.",
        rounds: "1",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Krish Panchani", contact: "8866799347" },
        ],
        imageSrc: "poster/Image_Gen.png",
      },
      {
        id: 20,
        category: "Non-Technical",
        date: "1 March",
        title: "Visual-vista",
        description: "Participants have to speake on the sequence of images shown within 2min.",
        rounds: "1",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "Meet Katarmal", contact: "9137674983" },
        ],
        imageSrc: "posters/visual_vista.svg",
      },
      {
        id: 21,
        category: "Non-Technical",
        date: "1 March & 2 March",
        title: "e-YuddhBhoomi",
        description: "Private rooms will be created and the participants will compete. Top3 person will win",
        rounds: "Depends On Participants",
        team: "2/3/4/5 Members",
        price: "60-100",
        coordinators: [
          { name: "Abhishek (VALO)", contact: "9974355597" },
          { name: "Praveen (VALO)", contact: "9327622985" },
          { name: "Mann (BGMI)", contact: "7575074341" },
          { name: "Jaydeep (BGMI)", contact: "7990643645" },
          { name: "Sahil (NSF)", contact: "9376059922" },
          { name: "Dwip (NSF)", contact: "9429108956" },
        ],
        imageSrc: "poster/e-yuddha.jpeg",
      },
      {
        id: 22,
        category: "Non-Technical",
        date: "1 March",
        title: "Sur Nirvaana",
        description: "Musical bands will perform at the end of the event.",
        rounds: "-",
        team: "-",
        price: "-",
        coordinators: [
          { name: "Hetarth Panchal", contact: "9328563827" },
        ],
        imageSrc: "poster/sur_nirvana.jpeg",
      },
      {
        id: 23,
        category: "Non-Technical",
        date: "1 March",
        title: "Chakravyuh",
        description: "Participants have to find the hints from the previous hints and the first team to leave the room/reach the final point will win.",
        rounds: "2",
        team: "4 Members",
        price: "100",
        coordinators: [
          { name: "Vasant", contact: "9316662350" },
        ],
        imageSrc: "poster/Chakrabyuh_.png",
      },
      {
        id: 24,
        category: "Non-Technical",
        date: "1 March",
        title: "FrameFusion",
        description: "Participants will be given a theme to capture and the best 3 will be selected/ Participants will be given a theme to capture and the best 3 will be selected",
        rounds: "1",
        team: "Solo/ 2 Members",
        price: "30/60",
        coordinators: [
          { name: "Sneh", contact: "9537064083" },
        ],
        imageSrc: "poster/Frame_Fusion.jpg",
      },
      {
        id: 25,
        category: "Non-Technical",
        date: "1 March",
        title: "WebJaal",
        description: "3 - 4 Websites given with 4 - 5 tasks to participants, and participants have to find the things (ex. Find the Perticular Article) given in 4 -5 tasks. ",
        rounds: "Depends on Participants",
        team: "Solo",
        price: "40",
        coordinators: [
          { name: "manmohan", contact: "7232010574" },
        ],
        imageSrc: "poster/web_jaal.jpeg",
      },
      {
        id: 26,
        category: "Non-Technical",
        date: "1 March",
        title: "Ascend-it",
        description: "Participants are given a particular sorting algorithm and each participant will be given a numerical value, then they're supposed to sort according to that algorithm.",
        rounds: "1",
        team: "5-7 Members",
        price: "100-140",
        coordinators: [
          { name: "Vaishanvi", contact: "6355384251" },
        ],
        imageSrc: "poster/Non_Tech_Sorting.jpeg",
      },
      {
        id: 27,
        category: "Non-Technical",
        date: "1 March",
        title: "Turbo Typing",
        description: "Time based typing test (Participants have to type given code).",
        rounds: "Depends on Participants",
        team: "Solo",
        price: "30",
        coordinators: [
          { name: "sahil sharma", contact: "9376059922" },
        ],
        imageSrc: "poster/Turbo_Typing.jpg",
      },
      {
        id: 28,
        category: "Non-Technical",
        date: "1 March",
        title: "Vishwa Parishad",
        description: "In a MUN conference, each student represents a country, organization, or person. Students role-play as UN delegates and engage in negotiations, discussions, and debates.",
        rounds: "2 Session",
        team: "Solo",
        price: "40",
        coordinators: [
          { name: "Jalshree Bhatt", contact: "9428299588" },
        ],
        imageSrc: "poster/vishwa_parishad.jpeg",
      },
      {
        id: 29,
        category: "Non-Technical",
        date: "1 March",
        title: "The Spotlight Showdown",
        description: "Singing, Dancing, Drama, Mime",
        rounds: "-",
        team: "Solo/ Team",
        price: "20 per person",
        coordinators: [
          { name: "Drashti", contact: "6354187793" },
          { name: "Ananya", contact: "9408574571" },
        ],
        imageSrc: "posters/The_spotlight_showdown.svg",
      },
      {
        id: 30,
        category: "Non-Technical",
        date: "2 March",
        title: "Strategic Stacks",
        description: "Specific amount will be given to participants & roundwise they will note the buying and selling of stocks. More profit gainer will be the winner.",
        rounds: "1",
        team: "Solo",
        price: "50",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "posters/Strategic_Stacks.svg",
      },
      {
        id: 31,
        category: "Non-Technical",
        date: "1 March",
        title: "Crazy Add",
        description: "Participants will receive a mystery product and have 30 Minutes to prepare a compelling presentation to sell it.",
        rounds: "1",
        team: "Solo",
        price: "50",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "posters/Crazy_Add.svg",
      },
      {
        id: 32,
        category: "Non-Technical",
        date: "2 March",
        title: "MINI SHARK TANK",
        description: "Participants (either solo or group) will pitch their ideas to sharks (faculties) and will try to convince them to invest in their product or service. The sharks will be given a fixed amount of fake money to invest. Winners will be decided on the basis of who secured highest funding ",
        rounds: "1",
        team: "Solo/ 2 Member",
        price: "20-40",
        coordinators: [
          { name: "Aryan", contact: "0000000000" },
        ],
        imageSrc: "poster/mini_sark.jpeg",
      },
      {
        id: 33,
        category: "Non-Technical",
        date: "1 March & 2 March",
        title: "Talent Tango",
        description: "Step into the shoes of your favourite fictional character and showcase your charisma and quick thinking in this HR-inspired event.",
        rounds: "2",
        team: "Solo",
        price: "50",
        coordinators: [
          { name: "Aryan", contact: "0000000000" },
        ],
        imageSrc: "posters/trailblazer.svg",
      },
      {
        id: 34,
        category: "Non-Technical",
        date: "1 March",
        title: "Laser Tag",
        description: "The players will have to detect and tag their opponents with the help of the laser gun.",
        rounds: "1",
        team: "Solo/Team",
        price: "50 per person",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "poster/Laser_Tag.jpeg",
      },
      {
        id: 35,
        category: "Non-Technical",
        date: "1 March",
        title: "FUTURIS TIC - build smart city.",
        description: "Planning & Designing of a future innovative smart city. Smart city – integration of all smart features [smart infrastructure, transportation, energy, water conservation etc.]",
        rounds: "1",
        team: "Solo/3 Member",
        price: "50/150",
        coordinators: [
          { name: "-", contact: "0000000000" },
        ],
        imageSrc: "poster/Non_Tech_Sorting.jpeg",
      },
];

